# ======================== Elasticsearch Configuration =========================
cluster.name: es-cluster
node.name: es-node01
node.master: false
node.data: true
discovery.seed_hosts: elasticsearch-master
cluster.initial_master_nodes: es-master,es-node01
http.port: 9201
transport.tcp.port: 9301
bootstrap.memory_lock: true