version: "3"
services:
    elasticsearch-node01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        container_name: elasticsearch-node01
        environment:
            - cluster.name=es-cluster
            - node.name=es-node01
            - node.master=false
            - node.data=true
            - discovery.seed_hosts=elasticsearch-master
            - cluster.initial_master_nodes=es-master,es-node01
            - http.port=9201
            - transport.tcp.port=9301
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms256m -Xmx256m
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
        - 9201:9201
        - 9301:9301
        restart: always
        volumes:
            # - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./data:/usr/share/elasticsearch/data:rw
            - ./logs:/usr/share/elasticsearch/logs:rw
        networks:
            - es-master_es-net
networks: # 创建网络
    es-master_es-net:
        external: true