version: "3"
services:
    es-tribe:
        image: elasticsearch:7.1.1
        container_name: es-tribe
        environment: # setting container env
            - ES_JAVA_OPTS=-Xms256m -Xmx256m   # set es bootstrap jvm args
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        restart: always
        volumes:
            - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./data:/usr/share/elasticsearch/data:rw
            - ./logs:/usr/share/elasticsearch/logs:rw
        network_mode: "host"