version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=es-single
      - node.name=es-single-node
      - http.port=9200
      - transport.tcp.port=9300
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      memlock:
          soft: -1
          hard: -1
      nofile:
          soft: 65536
          hard: 65536
    volumes:
      - ./data:/usr/share/elasticsearch/data:rw
      - ./logs:/usr/share/elasticsearch/logs:rw
    networks:
      - es-single-net
    ports:
      - 9200:9200
      - 9300:9300
  kibana711:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana711
    ports:
      - 5601:5601
    environment:
      # - server.name=kibana 
      # elasticSearch是容器名称, 这里, 集群要保证主节点对应的这个
      - elasticsearch.hosts=http://elasticsearch:9200
      - i18n.locale=zh-CN
    networks:
      - es-single-net
networks: # 创建网络
  es-single-net: