version: "3"
services:
    es-master:
        image: elasticsearch:7.1.1
        container_name: es-master
        environment: # setting container env
            - ES_JVM_OPTS=-Xms256m -Xmx256m   # set es bootstrap jvm args
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        restart: always
        volumes:
            - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./data:/usr/share/elasticsearch/data:rw
            - ./logs:/usr/share/elasticsearch/logs:rw
        network_mode: "host"
    es-head:
       image: tobias74/elasticsearch-head:6
       container_name: es-head
       restart: always
       ports:
       - "9100:9100"