# ======================== Elasticsearch Configuration =========================
cluster.name: es-cluster
node.name: es-master
node.master: true
node.data: false
discovery.seed_hosts: elasticsearch-node01
cluster.initial_master_nodes: es-master,es-node01
http.port: 9200
transport.tcp.port: 9300
bootstrap.memory_lock: true