# ======================== Elasticsearch Configuration =========================
cluster.name: es-cluster
node.name: tribe
node.master: false
node.data: false
node.attr.rack: r1 
bootstrap.memory_lock: true 
http.port: 9203
network.host: 0.0.0.0
transport.tcp.port: 9303
discovery.seed_hosts: ["es-master:9300","es-node01:9301","es-node02:9302","es-tribe:9303"] 
cluster.initial_master_nodes: ["master"] 
gateway.recover_after_nodes: 2

http.cors.enabled: true
http.cors.allow-origin: "*" 
discovery.zen.minimum_master_nodes: 1
xpack.security.enabled: false